### ISSUE TITLE
Add more flag parameters to upgrade_secret.go

### ISSUE THREAD

**Issue by makotonakai** [pepabo/locksmith#3]
## Background

Right now, upgrade_secret.go have several following fixed parameters. 
- namespace (currently, "default" is HARD CODED)
- secret name (currently, "tls-secret" is HARD CODED)

However, these parameters should have more flexibility, especially should be given from the command line, so that locksmith can support various cases that its users are facing.

## Purpose

 Support various cases (e.g. upgrade secret in namespace other than default, or the one whose name is different from "tls-secret")

## TODO

- [x] Add a "namespace" flag parameter
- [x] Add a "secret-name" flag parameter
- [x] Replace "default" with a variable for the given namespace
- [x] Replace "tls-secret" with a variable for the given secret name
