### ISSUE TITLE
Build a CI/CD pipeline to deploy a docker image

### ISSUE THREAD

**Issue by makotonakai** [pepabo/locksmith#4]
## Background

Right now, the docker image of locksmith can be built in a user's local environment by executing `docker build`.
However, in order to make it more convenient, the latest docker image should be released on this repository.

## Purpose

 Release the latest docker image on this repository, hopefully in an automated fashion.

## TODO

- [ ] Build a docker image
- [ ] Create a tag
- [ ] Push the docker image to GitHub container registry
- [ ] Release the docker image (and the source code) in the release section
