### ISSUE TITLE
Create a doc

### ISSUE THREAD

**Issue by makotonakai** [pepabo/locksmith#5]
## Background

Right now, people have no idea about how to use this software, because @makotonakai does not prepare any documents you would normally see in other open source software.

## Purpose

 Provide guidance about how to use locksmith with its users.
The document is going to become a part of README.md in the root directory.

## TODO

- [ ] Create a doc about how to create Root CA certificate and its private key
- [ ] Create a doc about how to create server certificate and its private key
- [ ] Create a doc about how to add locksmith in a k8s manifest file
